logging:
  level:
    io.github.jtsato.moviescatalog: info
    org.springframework.web: warn
    io.swagger.models.parameters.AbstractSerializableParameter: error
server:
  http2:
    enabled: true
  port: ${PORT:8081}
  error:
    whitelabel:
      enabled: true
spring:
  application:
    name: MoviesCatalog
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
    add-properties: false
  jackson:
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/db?useSSL=false
    username: root
    password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 600000
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        generate_statistics: false
        jdbc:
          batch_size: 30
          order_inserts: true
          order_updates: true
        cache:
          use_second_level_cache: false
        connection:
          provider_disables_autocommit: false
    hibernate:
      ddl-auto: update
  data:
    rest:
      detection-strategy: visibility
  h2:
    console:
      enabled: false
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  sql:
    init:
      encoding: UTF-8

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

okta:
  oauth2:
    clientId: ${OKTA_OAUTH2_CLIENT_ID:..}
    clientSecret: ${OKTA_OAUTH2_CLIENT_SECRET:..}}
    issuer: ${OKTA_OAUTH2_ISSUER:https://dev-507648.okta.com/oauth2/default}
    audience: api://default
    groups-claim: groups
